import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import '@/styles/globals.css'

export const metadata = {
  title: 'ClearTouch Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/images/logotwo.svg" />
      </head>
      <body className='max-w-[1800px] shadow-lg	 mx-auto'>
      <Navbar/>  
        {children}
        <Footer/>
      </body>
    </html>
  )
}
